---
abstract: 'Methods for getting localized CLDR language/territory names (and a subset of other data)'
author:
  - 'Daniel Muey <http://drmuey.com/cpan_contact.pl>'
build_requires:
  File::Slurp: '0'
  Module::Want: '0.6'
  Test::Carp: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.56'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.34, CPAN::Meta::Converter version 2.150001'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Locales
no_index:
  directory:
    - t
    - inc
requires:
  ExtUtils::MakeMaker: '6.56'
  File::Slurp: '0'
  Module::Want: '0.6'
  String::UnicodeUTF8: '0'
  Test::Carp: '0'
  Test::More: '0'
resources:
  bugtracker: https://github.com/drmuey/p5-Locales/issues
  repository: https://github.com/drmuey/p5-Locales.git
version: '0.34'
